{% set name = "bvpy" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.inria.fr/mosaic/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: e4d660f2e8880ace74109b9c805e1ee1f1c585f0a507943981ccd5229397a38c

build:
  skip: true  # [win or py<36]
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python =3.7
    - pip
    - setuptools
  run:
    - python =3.7
    - ipython
    - numpy
    - python-gmsh =4.5.6
    - nose
    - meshio
    - fenics
    - importlib_metadata
    - notebook
    - plotly
    - ipywidgets

test:
  source_files:
    - test
    - data
  requires:
    - pytest
    - pytest-cov
  commands:
    - pytest -v test

about:
  home: https://gitlab.inria.fr/mosaic/bvpy
  license: LGPL3
  license_file: LICENSE
  summary: Package providing tools to solve BVP (Boundary Value Problem) and IBVP (Initial Boundary Value Problem).
  dev_url: https://gitlab.inria.fr/mosaic/bvpy
  doc_source_url: https://mosaic.gitlabpages.inria.fr/bvpy/

extra:
  recipe-maintainers:
    - oalii
    - gcerutti
    - jlegrand62
